apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xenserver-test-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage:
        1Gi
  storageClassName: nfs
