apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - image: {{ .Values.image }}
          name: {{ .Values.name }}
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}
          volumeMounts:
            - name: base-share
              mountPath: {{ quote .Values.config.fakePath }}
      volumes:
        - name: base-share
          nfs:
            server: {{ quote .Values.config.server }}
            path: {{ quote .Values.config.mountPath }}

